<?php echo $this->doctype(); ?>

<html ng-app="jaztecCms" ng-controller="PageCtrl" lang="nl">
  <head>
      <title ng-bind="page.Title"></title>
      <meta name="description" content="{{page.Description}}">
      <?php echo $this->angularJsApp() ?>
      <?php echo $this->cms()->meta(); ?>
      <?php echo $this->cms()->link(); ?>
      <?php echo $this->cms()->script();  ?>
  </head>
  <body>
      <?php echo $this->content; ?>
  </body>
</html>
